/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellBrainRouteImport } from './routes/_shell.brain'
import { Route as ShellChatRouteImport } from './routes/_shell.chat'
import { Route as ShellCreateRouteImport } from './routes/_shell.create'
import { Route as ShellHomeRouteImport } from './routes/_shell.home'
import { Route as ShellLibraryRouteImport } from './routes/_shell.library'
import { Route as ShellCreateIndexRouteImport } from './routes/_shell.create.index'
import { Route as ShellCreateReviewRouteImport } from './routes/_shell.create.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellBrainRoute = ShellBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreateRoute = ShellCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeRoute = ShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreateIndexRoute = ShellCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellCreateRoute,
} as any)
const ShellCreateReviewRoute = ShellCreateReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ShellCreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof ShellBrainRoute
  '/chat': typeof ShellChatRoute
  '/create': typeof ShellCreateRouteWithChildren
  '/home': typeof ShellHomeRoute
  '/library': typeof ShellLibraryRoute
  '/create/review': typeof ShellCreateReviewRoute
  '/create/': typeof ShellCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof ShellBrainRoute
  '/chat': typeof ShellChatRoute
  '/home': typeof ShellHomeRoute
  '/library': typeof ShellLibraryRoute
  '/create/review': typeof ShellCreateReviewRoute
  '/create': typeof ShellCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/brain': typeof ShellBrainRoute
  '/_shell/chat': typeof ShellChatRoute
  '/_shell/create': typeof ShellCreateRouteWithChildren
  '/_shell/home': typeof ShellHomeRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/create/review': typeof ShellCreateReviewRoute
  '/_shell/create/': typeof ShellCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/chat'
    | '/create'
    | '/home'
    | '/library'
    | '/create/review'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/chat'
    | '/home'
    | '/library'
    | '/create/review'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/brain'
    | '/_shell/chat'
    | '/_shell/create'
    | '/_shell/home'
    | '/_shell/library'
    | '/_shell/create/review'
    | '/_shell/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/brain': {
      id: '/_shell/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof ShellBrainRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/create': {
      id: '/_shell/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof ShellCreateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home': {
      id: '/_shell/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ShellHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/create/': {
      id: '/_shell/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof ShellCreateIndexRouteImport
      parentRoute: typeof ShellCreateRoute
    }
    '/_shell/create/review': {
      id: '/_shell/create/review'
      path: '/review'
      fullPath: '/create/review'
      preLoaderRoute: typeof ShellCreateReviewRouteImport
      parentRoute: typeof ShellCreateRoute
    }
  }
}

interface ShellCreateRouteChildren {
  ShellCreateReviewRoute: typeof ShellCreateReviewRoute
  ShellCreateIndexRoute: typeof ShellCreateIndexRoute
}

const ShellCreateRouteChildren: ShellCreateRouteChildren = {
  ShellCreateReviewRoute: ShellCreateReviewRoute,
  ShellCreateIndexRoute: ShellCreateIndexRoute,
}

const ShellCreateRouteWithChildren = ShellCreateRoute._addFileChildren(
  ShellCreateRouteChildren,
)

interface ShellRouteChildren {
  ShellBrainRoute: typeof ShellBrainRoute
  ShellChatRoute: typeof ShellChatRoute
  ShellCreateRoute: typeof ShellCreateRouteWithChildren
  ShellHomeRoute: typeof ShellHomeRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBrainRoute: ShellBrainRoute,
  ShellChatRoute: ShellChatRoute,
  ShellCreateRoute: ShellCreateRouteWithChildren,
  ShellHomeRoute: ShellHomeRoute,
  ShellLibraryRoute: ShellLibraryRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
